basePath: /api/v1
definitions:
  main.ReqAdd:
    properties:
      dbID:
        type: integer
      xb:
        items:
          type: number
        type: array
      xid:
        type: integer
    type: object
host: '{{.Host}}'
info:
  contact:
    email: yuzhichang@gmail.com
    name: API Support
    url: https://github.com/infinivision/vectodb/issues
  description: This is a VectoDBLite cluster server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: VectoDBLite Cluster API
  version: "1.0"
paths:
  /api/v1/add:
    post:
      consumes:
      - application/json
      description: Add a vector to the given vectodblite
      parameters:
      - description: ReqAdd. If xid is not specified, the cluster will generate one.
        in: body
        name: add
        required: true
        schema:
          $ref: '#/definitions/main.ReqAdd'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: int
        "300":
          description: redirect to another node!
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
swagger: "2.0"
