import os.path
import os

Import("env")

# Every .cpp is a standalone program.
for filename in ['demo_sift1M.cpp', 'faiss_train.cpp', 'faiss_search.cpp', 'generate_dataset.cpp']:
	exename = os.path.splitext(filename)[0] 
	env.Program(exename, filename, LIBS=['faiss', 'openblas', 'stdc++fs'])

# https://stackoverflow.com/questions/33149878/experimentalfilesystem-linker-error/33159746#33159746
for filename in ['demo_sift1M_vectodb.cpp']:
	exename = os.path.splitext(filename)[0] 
	env.Program(exename, filename, LIBS=['vectodb', 'faiss', 'openblas', 'glog', 'gflags', 'stdc++fs'])
