import os.path
import os
import glob

Import("env")

# Every .cpp is a standalone program.
cfiles = glob.glob("*.cpp")
for filename in cfiles:
	exename = os.path.splitext(filename)[0] 
	env.Program(exename, filename, LIBS=['faiss', 'openblas'], )
