import os.path
import os

Import("env")

# Every .cpp is a standalone program.
env.Append(LIBPATH='/usr/local/opt/openblas/lib')
env.Append(LIBPATH='/usr/local/opt/boost/lib')
for filename in ['demo_sift1M.cpp', 'faiss_train.cpp', 'faiss_search.cpp']:
	exename = os.path.splitext(filename)[0] 
	env.Program(exename, filename, LIBS=['faiss', 'openblas'], )

for filename in ['demo_sift1M_vectodb.cpp']:
	exename = os.path.splitext(filename)[0] 
	env.Program(exename, filename, LIBS=['vectodb', 'faiss', 'openblas', 'boost_thread-mt', 'boost_filesystem', 'boost_system', 'glog', 'gflags'], )
